<?php

namespace DataBundle\Repository;

/**
 * ProverbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProverbRepository extends \Doctrine\ORM\EntityRepository
{
}
